/**
 * 文档案例基准（供 tests/test.html 与 tests/node-check.mjs 共用）
 * approx: true 表示文档基准值来自历史票价表查表，公式近似存在个位数偏差
 */
export const CASES = [
  // ── 标准票价（严格比对）──
  { id: '案例1', desc: 'K419 西安-咸阳 硬座快速新空调全价（23km）', expect: 9,
    p: { seatKey: 'yz', level: 'kuaisu', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 23, mode: 'standard' }] } },
  { id: '案例2', desc: 'Z88 西安-南京 软卧下特快新空调全价（1208km）', expect: 427.5,
    p: { seatKey: 'rw_xia', level: 'tekuai', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 1208, mode: 'standard' }] } },
  { id: '案例3', desc: 'Z164 南京-西安 硬卧中特快新空调学生票（1208km）', expect: 194.5,
    p: { seatKey: 'yw_zhong', level: 'tekuai', ac: true, acRate: 0.5, ticket: 'student', sleeperDiscount: 'none',
         segments: [{ km: 1208, mode: 'standard' }] } },
  { id: '案例4a', desc: '7001 西安-钟家村 硬座普客非空调（126km）', expect: 8.5,
    p: { seatKey: 'yz', level: 'putong', ac: false, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 126, mode: 'standard' }] } },
  { id: '案例4b', desc: '7001 西安-三原（69km）', expect: 4,
    p: { seatKey: 'yz', level: 'putong', ac: false, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 69, mode: 'standard' }] } },
  { id: '案例4c', desc: '7001 三原-钟家村（57km）', expect: 3,
    p: { seatKey: 'yz', level: 'putong', ac: false, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 57, mode: 'standard' }] } },
  // ── 非标准票价（严格比对）──
  { id: '例1a', desc: 'K1071 合肥-怀宁 硬座（19+137km 非标准分段折算）', expect: 29.5,
    p: { seatKey: 'yz', level: 'kuaisu', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 19, mode: 'standard', prorate: true }, { km: 137, mode: 'standard', prorate: true }] } },
  { id: '例1b', desc: 'T221 合肥-怀宁 硬座特快新空调（156km 标准参照）', expect: 23.5,
    p: { seatKey: 'yz', level: 'tekuai', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 156, mode: 'standard' }] } },
  { id: '例9a', desc: 'K351 安康-成都 硬座快速新空调（765km 国铁）', expect: 102,
    p: { seatKey: 'yz', level: 'kuaisu', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 765, mode: 'standard' }] } },
  { id: '例9b', desc: 'K117 安康-成都西 硬座（达成线186km + 国铁482km）', expect: 104,
    p: { seatKey: 'yz', level: 'kuaisu', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 186, mode: 'dacheng' }, { km: 482, mode: 'standard' }] } },
  // ── 文档参考值（查表基准，公式近似）──
  { id: '例2', desc: 'Z8002 长沙-张家界西 硬座（国铁155 + 石长900km运价+1/2 184km）', expect: 68.5, approx: true,
    p: { seatKey: 'yz', level: 'kuaisu', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 184, mode: 'km900', u: 0.5 }, { km: 155, mode: 'standard' }] } },
  { id: '例3', desc: 'T253 长沙-广州 软卧下（国铁399 + 坪广900km运价+1/2 308km）', expect: 320, approx: true,
    p: { seatKey: 'rw_xia', level: 'tekuai', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 308, mode: 'km900', u: 0.5 }, { km: 399, mode: 'standard' }] } },
  { id: '例4', desc: 'K9064 深圳西-广州 硬座（平南×3 35km + 广深双浮 127km）', expect: 65.5, approx: true,
    p: { seatKey: 'yz', level: 'kuaisu', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 35, mode: 'times', factor: '3', berthFactor: '1.5', prorate: true },
                    { km: 127, mode: 'times', factor: '1.5,1.3', berthFactor: '1.5' }] } },
  { id: '例5', desc: 'K9218 深圳-广州北 硬座（非标准88km + 国铁70km）', expect: 40.5, approx: true,
    p: { seatKey: 'yz', level: 'kuaisu', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 88, mode: 'km900', u: 0.5 }, { km: 70, mode: 'standard' }] } },
  { id: '例6', desc: 'K34 深圳-龙川 硬座（深圳-常平57km ×1/2 + 常平-龙川213km ×7/20）', expect: 56.5, approx: true,
    p: { seatKey: 'yz', level: 'kuaisu', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 57, mode: 'km900', u: 0.5 }, { km: 213, mode: 'km900', u: 0.35 }] } },
  { id: '例7', desc: 'K9263 肇庆-茂名 硬座（900km运价+7/20 252km）', expect: 48.5, approx: true,
    p: { seatKey: 'yz', level: 'kuaisu', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 252, mode: 'km900', u: 0.35 }] } },
  { id: '例8', desc: 'Z501 北京西-三亚 硬座（国铁2669 + 茂湛80 + 塘口-三亚681）', expect: 435, approx: true,
    p: { seatKey: 'yz', level: 'tekuai', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 2669, mode: 'standard' },
                    { km: 80, mode: 'times', factor: '1.5', berthFactor: '3', prorate: true },
                    { km: 681, mode: 'times', factor: '1.5', berthFactor: '3', prorate: true }] } },
  { id: '例10', desc: 'Z165 西宁-拉萨 硬卧下（国铁合并1972 + 青藏加价1142）', expect: 521, approx: true,
    p: { seatKey: 'yw_xia', level: 'tekuai', ac: true, acRate: 0.5, ticket: 'full', sleeperDiscount: 'none',
         segments: [{ km: 1972, mode: 'standard' }, { km: 1142, mode: 'qz' }] } },
];
